// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import AutoRefreshController from "./auto_refresh_controller"
application.register("auto-refresh", AutoRefreshController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import GenerationAnimationController from "./generation_animation_controller"
application.register("generation-animation", GenerationAnimationController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NewsletterController from "./newsletter_controller"
application.register("newsletter", NewsletterController)
