// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import AutoRefreshController from "./auto_refresh_controller"
application.register("auto-refresh", AutoRefreshController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import GenerationAnimationController from "./generation_animation_controller"
application.register("generation-animation", GenerationAnimationController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MobileMenuController from "./mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)

import EditorialNavController from "./editorial_nav_controller"
application.register("editorial-nav", EditorialNavController)

import NavbarScrollController from "./navbar_scroll_controller"
application.register("navbar-scroll", NavbarScrollController)

import NewsletterController from "./newsletter_controller"
application.register("newsletter", NewsletterController)

import ScrollRevealController from "./scroll_reveal_controller"
application.register("scroll-reveal", ScrollRevealController)

import AccordionController from "./accordion_controller"
application.register("accordion", AccordionController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import ViewToggleController from "./view_toggle_controller"
application.register("view-toggle", ViewToggleController)

import KanbanController from "./kanban_controller"
application.register("kanban", KanbanController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import TemplateSelectController from "./template_select_controller"
application.register("template-select", TemplateSelectController)

import DeveloperCardController from "./developer_card_controller"
application.register("developer-card", DeveloperCardController)

import ChatScrollController from "./chat_scroll_controller"
application.register("chat-scroll", ChatScrollController)

import ChatFormController from "./chat_form_controller"
application.register("chat-form", ChatFormController)

import ChatWidgetController from "./chat_widget_controller"
application.register("chat-widget", ChatWidgetController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import FileUploadController from "./file_upload_controller"
application.register("file-upload", FileUploadController)

import JobUrlFetcherController from "./job_url_fetcher_controller"
application.register("job-url-fetcher", JobUrlFetcherController)

import ResumeWizardController from "./resume_wizard_controller"
application.register("resume-wizard", ResumeWizardController)

import AtsCheckerController from "./ats_checker_controller"
application.register("ats-checker", AtsCheckerController)

import ScoreGaugeController from "./score_gauge_controller"
application.register("score-gauge", ScoreGaugeController)

import HireModalController from "./hire_modal_controller"
application.register("hire-modal", HireModalController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import CurrencyToggleController from "./currency_toggle_controller"
application.register("currency-toggle", CurrencyToggleController)
