[phases.setup]
nixPkgs = ['nodejs', 'yarn']

[phases.install]
cmds = [
    'bundle install',
    'yarn install --frozen-lockfile'
]

[phases.build]
cmds = [
    'bundle exec rake assets:precompile'
]

[start]
cmd = 'bundle exec puma -C config/puma.rb'